// <auto-generated />
using System;
using EnergyMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyMonitor.Api.Migrations
{
    [DbContext(typeof(EnergyMonitorContext))]
    partial class EnergyMonitorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("EnergyMonitor.Models.Aparelho", b =>
                {
                    b.Property<int>("AparelhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConsumoMedioWatts")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AparelhoId");

                    b.ToTable("Aparelhos");
                });

            modelBuilder.Entity("EnergyMonitor.Models.Leitura", b =>
                {
                    b.Property<int>("LeituraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AparelhoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConsumoAtualWatts")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CorrenteAmperes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TensaoVolts")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("LeituraId");

                    b.HasIndex("AparelhoId");

                    b.ToTable("Leituras");
                });

            modelBuilder.Entity("EnergyMonitor.Models.Leitura", b =>
                {
                    b.HasOne("EnergyMonitor.Models.Aparelho", "Aparelho")
                        .WithMany("Leituras")
                        .HasForeignKey("AparelhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aparelho");
                });

            modelBuilder.Entity("EnergyMonitor.Models.Aparelho", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
